name: Test Cygwin

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-minor-version: [8]
        architecture: ["x86"]

    name: Python 3.8 x86

    steps:
      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@v2
        with:
          platform: ${{ matrix.architecture }}
          packages: >
            python3${{ matrix.python-minor-version }}-pip

      - name: Build
        shell: bash.exe -o igncr "{0}"
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade coverage
          python3 -c "import coverage;print(coverage)"
